kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
spec:
  type: LoadBalancer
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        
---

kind: Endpoints
apiVersion: v1
metadata:
  name: train-schedule-service
subsets:
  - addresses:
      - ip: 192.168.233.15
    ports:
      - port: 8080
 
